### ISSUE TITLE
Follower notifications in feed / separate

### ISSUE THREAD

**Issue by cliftonc** [tes/seguir#35]
Looking at twitter this morning, they have the follower notifications out into a separate feed - 'notifications', and roll things up by day - e.g. X people followed you on Jun-14.

<img width="1234" alt="screen shot 2015-07-17 at 06 12 46" src="https://cloud.githubusercontent.com/assets/239305/8741027/c96992be-2c4a-11e5-8c3d-69f691286de3.png">

We should consider this /cc @MikaelaB @dmorgantini - wouldn't be a difficult refactor seguir side.  We could keep these notifications on the same page though, or push into the profile.

**Comment by cliftonc** [comment]
You could also just do this in the feed itself (e.g. if you have multiple follow events on a page, just roll them all up and display them in single cards).

**Comment by dmorgantini** [comment]
I wonder if this sort of thing is not the responsibility of seguir and rather up to the consuming application to decide how to render feed items, how feed items should be aggregated, etc?

**Comment by dmorgantini** [comment]
Thought a separate 'feed' concept such as notifications_timeline, might be useful - though I'm not sure how it differs from the user_timeline so perhaps we should discuss.

**Comment by MikaelaB** [comment]
We had planned for it to be separated out in early discussions then merged into one column for mobile. This was the mvp version. I think merging all follow into one card would be an elegant solution, but needs thinking out for 2nd follows.




On 17 Jul 2015, at 10:01, David Morgantini <notifications@github.com<mailto:notifications@github.com>> wrote:


Thought a separate 'feed' concept such as notifications_timeline, might be useful - though I'm not sure how it differs from the user_timeline so perhaps we should discuss.

—
Reply to this email directly or view it on GitHub<https://github.com/cliftonc/seguir/issues/35#issuecomment-122222946>.
This e-mail message, including any attachments transmitted with it, is CONFIDENTIAL and may contain legally privileged or private information. This message is intended solely for the use of the individual or entity to whom it is addressed. 

 

If you have received this message in error, please notify the sender or security@tsleducation.com immediately and delete it from your system. You should not copy, store or use this email or any attachment(s) for any purpose, nor disclose their contents to any other person. 

 

E-mail is not a 100% virus-free or secure medium. Whilst TSL scans all communications for viruses or other malicious software, we do not guarantee that this message is virus-free and accept no liability for any potential loss or damage that may arise as a result of receiving, storing and reading this message and any attachment(s).  It is your responsibility to ensure that viruses do not adversely affect your system and that your messages to us meet your own security requirements. 

 

We reserve the right to read any e-mail or attachment entering or leaving our systems without notice.

 

TSL Education is a limited company registered in England and Wales (Company number 02017289) with its registered office at 26 Red Lion Square, London, WC1R 4HQ.

**Comment by cliftonc** [comment]
Ok - I'll leave as a client side feature for now, and we can revisit later.
