### ISSUE TITLE
Bring Seguir to the Promise(d) land

### ISSUE THREAD

**Issue by dmorgantini** [tes/seguir#49]
I'd use Bluebird as it's leader in class right now and integrates with ES6 promises.

We may want to do a hybrid concept where if next is null then return a promise - or just go whole hog.  Bring Clifton into the 21st century.

**Comment by tomruttle** [comment]
+1

**Comment by cliftonc** [comment]
Nothing against it, but I suspect it's a pretty heft re-factor unless you just write a wrapper around the final API (e.g. not worry about the fact that all of the internal API interactions are still callback based).  Is this the plan?

I still find callbacks easier to reason about, but I know I'm just being old and boring.
